### ISSUE TITLE
Visualization tool stopping at BigBED file

### ISSUE THREAD

**Issue by JenHauen16** [jorvis/GALES#16]
I have tried to visualize the output of 2 different bacteria genomes with no success. It stops at the BigBED file.
This is run on a Ubuntu vm.

jen@jen-VirtualBox:~/GALES/bin/viewtest$ /home/jen/GALES/bin/view_annotation -i /home/jen/GALES/bin/viewtest/ -f /home/jen/GALES/bin/GCA_002430675.1_ASM243067v1_genomic.fna
Removing existing UI data path: /home/jen/GALES/ui/data
Creating symlink to UI data path: /home/jen/GALES/ui/data

--------------------------------------------------------------------------------
Checking for stored statistics and analyses within input directory, or creating them.
This can cause the first execution on any input directory to take a few minutes.
--------------------------------------------------------------------------------

Checking for FASTA stats file ... not found. Parsing ... done.
Checking for stored GFF features file ... not found. Parsing ... done.
Checking for GFF stats file ... not found.  Parsing ... done.
Checking for binary version of reference genome FASTA ... not found.  Creating ... done.
Checking for reference genome FASTA sizes file ... not found.  Creating ... done.
Checking for annotation BED file ... not found.  Creating ... done.
Checking for sorted annotation BED file ... not found.  Creating ... done.
Checking for bigBed annotation file ... not found.  Creating ... pass1 - making usageList (3 chroms): 1 millis
pass2 - checking and writing primary data (1234 records, 12 fields): 20 millis
done.
Checking for BLAST BED file ... not found.  Creating ... done.
Checking for sorted BLAST BED file ... not found.  Creating ... done.
Checking for BLAST bigBED file ... not found.  Creating ... End coordinate 78279 bigger than DJCT01000002.1 size of 78276 line 18097 of /home/jen/GALES/bin/viewtest/rapsearch2.out.bed.sorted
Traceback (most recent call last):
  File "/home/jen/GALES/bin/view_annotation", line 437, in <module>
    main()
  File "/home/jen/GALES/bin/view_annotation", line 151, in main
    run_command_by_file_presence(blast_bb_file, "BLAST bigBED file", cmd)
  File "/home/jen/GALES/bin/view_annotation", line 333, in run_command_by_file_presence
    run_command(cmd)
  File "/home/jen/GALES/bin/view_annotation", line 326, in run_command
    raise Exception("ERROR: [{2}] Return code {0} when running the following command: {1}".format(return_code, cmd, datetime.datetime.now()))
Exception: ERROR: [2019-04-23 19:52:16.386182] Return code 255 when running the following command: /home/jen/GALES/bin/Linux/bedToBigBed /home/jen/GALES/bin/viewtest/rapsearch2.out.bed.sorted /home/jen/GALES/bin/viewtest/genome.sizes /home/jen/GALES/bin/viewtest/rapsearch2.out.bb
jen@jen-VirtualBox:~/GALES/bin/viewtest$ /home/jen/GALES/bin/view_annotation -i /home/jen/GALES/bin/output2/ -f /home/jen/GALES/bin/GCA_001580535.1_ASM158053v1_genomic.fna 
Removing existing UI data path: /home/jen/GALES/ui/data
Creating symlink to UI data path: /home/jen/GALES/ui/data

--------------------------------------------------------------------------------
Checking for stored statistics and analyses within input directory, or creating them.
This can cause the first execution on any input directory to take a few minutes.
--------------------------------------------------------------------------------

Checking for FASTA stats file ... found.
Checking for stored GFF features file ... found.
Checking for GFF stats file ... found.
Checking for binary version of reference genome FASTA ... found.
Checking for reference genome FASTA sizes file ... found.
Checking for annotation BED file ... found.
Checking for sorted annotation BED file ... found.
Checking for bigBed annotation file ... not found.  Creating ... End coordinate 743 bigger than LHZA01000009.1 size of 738 line 12 of /home/jen/GALES/bin/output2/attributor.annotation.bed.sorted
Traceback (most recent call last):
  File "/home/jen/GALES/bin/view_annotation", line 437, in <module>
    main()
  File "/home/jen/GALES/bin/view_annotation", line 140, in main
    run_command_by_file_presence(annotation_bb_file, "bigBed annotation file", cmd)
  File "/home/jen/GALES/bin/view_annotation", line 333, in run_command_by_file_presence
    run_command(cmd)
  File "/home/jen/GALES/bin/view_annotation", line 326, in run_command
    raise Exception("ERROR: [{2}] Return code {0} when running the following command: {1}".format(return_code, cmd, datetime.datetime.now()))
Exception: ERROR: [2019-04-23 19:53:33.023896] Return code 255 when running the following command: /home/jen/GALES/bin/Linux/bedToBigBed /home/jen/GALES/bin/output2/attributor.annotation.bed.sorted /home/jen/GALES/bin/output2/genome.sizes /home/jen/GALES/bin/output2/attributor.annotation.bb

**Comment by jorvis** [comment]
I have seen this a few times but don't have an input file to test it.  It seems one of the prediction tools is exporting coordinates outside of the range of the actual molecule.  Would you mind attaching your input file?
